# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         FileHash
version:      0.01-2
version_from: Version
installdirs:  site
requires:
    Cwd:                           0
    Digest::MD5:                   0
    Exporter:                      0
    Fault::Logger:                 0
    File::Spec:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
